apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux
resources:
  - miniflux-deploy.yml
  - miniflux-svc.yml
  - miniflux-ing.yml
  - miniflux-pvc.yml
  - miniflux-spc.yml
  - miniflux-sa.yml
  - miniflux-ns.yml
  - psql-deploy.yml
  - psql-svc.yml
