apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: miniflux 
spec:
  provider: vault
  secretObjects:
  - secretName: miniflux
    type: Opaque
    data: 
    - objectName: POSTGRES_DB
      key: POSTGRES_DB
    - objectName: POSTGRES_PASSWORD
      key: POSTGRES_PASSWORD
    - objectName: POSTGRES_USER
      key: POSTGRES_USER
    - objectName: DATABASE_URL
      key: DATABASE_URL
    - objectName: ADMIN_PASSWORD
      key: ADMIN_PASSWORD
    - objectName: OAUTH2_CLIENT_ID
      key: OAUTH2_CLIENT_ID
    - objectName: OAUTH2_CLIENT_SECRET 
      key: OAUTH2_CLIENT_SECRET 
    - objectName: OAUTH2_OIDC_DISCOVERY_ENDPOINT 
      key: OAUTH2_OIDC_DISCOVERY_ENDPOINT 
    - objectName: OAUTH2_REDIRECT_URL
      key: OAUTH2_REDIRECT_URL
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: miniflux
    objects: |
      - objectName: "POSTGRES_DB"
        secretPath: "apps-kv/data/miniflux/database"
        secretKey: "POSTGRES_DB"
      - objectName: "POSTGRES_PASSWORD"
        secretPath: "apps-kv/data/miniflux/database"
        secretKey: "POSTGRES_PASSWORD"
      - objectName: "POSTGRES_USER"
        secretPath: "apps-kv/data/miniflux/database"
        secretKey: "POSTGRES_USER"
      - objectName: "DATABASE_URL"
        secretPath: "apps-kv/data/miniflux/database"
        secretKey: "DATABASE_URL"
      - objectName: "ADMIN_PASSWORD"
        secretPath: "apps-kv/data/miniflux/config"
        secretKey: "ADMIN_PASSWORD"
      - objectName: "OAUTH2_CLIENT_ID"
        secretPath: "apps-kv/data/miniflux/config"
        secretKey: "OAUTH2_CLIENT_ID"
      - objectName: "OAUTH2_CLIENT_SECRET"
        secretPath: "apps-kv/data/miniflux/config"
        secretKey: "OAUTH2_CLIENT_SECRET"
      - objectName: "OAUTH2_OIDC_DISCOVERY_ENDPOINT"
        secretPath: "apps-kv/data/miniflux/config"
        secretKey: "OAUTH2_OIDC_DISCOVERY_ENDPOINT"
      - objectName: "OAUTH2_REDIRECT_URL"
        secretPath: "apps-kv/data/miniflux/config"
        secretKey: "OAUTH2_REDIRECT_URL"
