---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: miniflux-psql
  annotations:
    nfs.io/storage-path: "data01/miniflux/db"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
